require("symbols-outline").setup({
  highlight_hovered_item = false,
  relative_width = false,
  width = 55,
  show_symbol_details = false,
  symbol_blacklist = {
    "Constructor",
  },
  symbols = {
    File = { icon = "file", hl = "@text.uri" },
    Module = { icon = "module", hl = "@namespace" },
    Namespace = { icon = "namespace", hl = "@namespace" },
    Package = { icon = "package", hl = "@namespace" },
    Class = { icon = "type", hl = "@type" },
    Method = { icon = "method", hl = "@method" },
    Property = { icon = "property", hl = "@method" },
    Field = { icon = "field", hl = "@field" },
    Constructor = { icon = "ctor", hl = "@constructor" },
    Enum = { icon = "enum", hl = "@type" },
    Interface = { icon = "interface", hl = "@type" },
    Function = { icon = "func", hl = "@function" },
    Variable = { icon = "var", hl = "@constant" },
    Constant = { icon = "const", hl = "@constant" },
    String = { icon = "str", hl = "@string" },
    Number = { icon = "num", hl = "@number" },
    Boolean = { icon = "bool", hl = "@boolean" },
    Array = { icon = "arr", hl = "@constant" },
    Object = { icon = "obj", hl = "@type" },
    Key = { icon = "key", hl = "@type" },
    Null = { icon = "", hl = "@type" },
    EnumMember = { icon = "const", hl = "@constant" },
    Struct = { icon = "type", hl = "@type" },
    Event = { icon = "event", hl = "@type" },
    Operator = { icon = "op", hl = "@operator" },
    TypeParameter = { icon = "param", hl = "@parameter" },
    Component = { icon = "component", hl = "@function" },
    Fragment = { icon = "fragment", hl = "@constant" },
  },
  fold_markers = { '→', '⬐' },
})

